# Generated by Django 5.2 on 2025-04-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinyl',
            name='genre',
            field=models.CharField(choices=[('rock', 'Rock'), ('pop', 'Pop'), ('jazz', 'Jazz'), ('classical', 'Classical'), ('hiphop', 'Hip-Hop'), ('metal', 'Metal'), ('blues', 'Blues'), ('electronic', 'Electronic')], default='pop', max_length=50),
        ),
    ]
