# Generated by Django 5.2 on 2025-04-06 16:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_vinyl_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinyl',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
