# Generated by Django 5.2 on 2025-04-10 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_category_vinyl_categories_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
