# Generated by Django 5.2 on 2025-04-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinyl',
            name='categories',
            field=models.ManyToManyField(blank=True, to='home.category'),
        ),
    ]
